---
Mailstore:            "./Maildir"
WebUIDir:             "./www"
Debug:                true
TrustForwarded:       true
#TwilioAccountID:      $TWILIO_ACCOUNTID
#TwilioAuthToken:      $TWILIO_TOKEN
GroupDomain:          "periwinkle.lol"
#WebRoot:              "http://$HOSTNAME:8080"
CallbackConnect:      "localhost:42586"
CallbackListen:       "localhost:42586"
# DB:
#   driver: mysql
#   source: "username:password@hostname/database?charset=utf8&parseTime=True"
# DB:
#   driver: sqlite3
#   source: "file:periwinkle.sqlite?mode=rwc&_txlock=exclusive"
